#ifndef _CONFIGURATION_H
#define _CONFIGURATION_H

#define MAX_USER_NAME_LENGTH 10
#define MAX_USER_ID_LENGTH 10
#define MAX_USER_COUNT 10

#define MAX_ACCESS_QUEUE_LENGTH 10

#define LOG_QUEUE_MAX_LENGTH 16
#define LOG_MESSAGE_MAX_LENGTH 128

#define LOGGER_ERROR LogLevel::ERROR
#define LOGGER_WARN  LogLevel::WARN
#define LOGGER_INFO  LogLevel::INFO
#define LOGGER_DEBUG LogLevel::DEBUG
#define LOGGER_MIN_VALID_TIME 1735664400 // 2025-01-21T00:00:00+07:00

#endif